# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bcf4a35d776d0c4a9ae623d54cb1fa87c2ad35c60e37c4f8943d8c7e69fd2327965e84594844895bcb5bd9d6812c14c8fcb0bf222058e996409b7927a7f5902

test:
  secret_key_base: 70d045f2e53de9621280fe01fdb74a34d3ac127813ac11fea690c06055622f80956d0f1bc545b96b5343a9d5e901de80f7231487807cd56367c2e57d4ddde758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
